version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=testtest
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web-app:
    image: epperic/studienuebersicht
    ports:
      - 8080:80
    environment:
      - PERSISTENCE_METHOD=efcore
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_PASSWORD=testtest

  api:
    image: epperic/studienuebersichtapi
    ports:
      - 8081:80
    environment:
      - PERSISTENCE_METHOD=efcore
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_PASSWORD=testtest

volumes:
  postgres-data: